[validation]
num_hyperparameter_configs = 20
use_focused_search = false

[pso]
N = 80
C1 = 1.8
C2 = 1.3
omega = 0.45
f_calls_limit = 1500

[optimization]
use_lm = true
temporal_penalty_weight = 0.01

[outlier_detection]
mad_threshold = 12.0
fator_liq = 0.015