[validation]
num_hyperparameter_configs = 20

[pso]
N = 80
C1 = 1.8
C2 = 1.3
omega = 0.45
f_calls_limit = 1500
# Bounds balanceados: flexibilidade matemática + realismo econômico
lower_bounds = [0.02, -0.20, -0.35, -0.35, 0.2, 0.3]
upper_bounds = [0.40, 0.20, 0.20, 0.20, 12.0, 25.0]

[optimization]
use_lbfgs = true
temporal_penalty_weight = 0.01

[outlier_detection]
mad_threshold = 12.0
fator_liq = 0.015

[fit_curves]
continuity_search_days = 30
min_bonds_for_fit = 3
lbfgs_max_iterations = 50
reoptimization_cost_multiplier = 10.0
reoptimization_pso_multiplier = 2.0

[animation]
fps = 10
duration = 30
maturities = [0.25, 0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0]
plot_dpi = 200
plot_size = [1200, 800]

[cross_validation]
max_cores = 8
train_max_iterations = 2
lbfgs_max_iterations_cv = 50
stability_vertices = [0.5, 1.0, 3.0, 5.0, 10.0, 15.0]

[cross_validation.bayesian_objective_scaling]
cost_score = 50.0
stability_score = 20.0
overfitting_penalty = 2.0

[cross_validation.hybrid_score_weights]
test = 0.5
stability = 0.3
overfitting = 0.2

[[cross_validation.blocks]]
train_start = "2015-02-01"
train_end = "2015-02-28"
test_start = "2015-03-01"
test_end = "2015-03-31"

[[cross_validation.blocks]]
train_start = "2016-07-01"
train_end = "2016-07-31"
test_start = "2016-08-01"
test_end = "2016-08-31"

[[cross_validation.blocks]]
train_start = "2018-05-01"
train_end = "2018-05-31"
test_start = "2018-06-01"
test_end = "2018-06-30"

[[cross_validation.blocks]]
train_start = "2020-02-01"
train_end = "2020-02-29"
test_start = "2020-03-01"
test_end = "2020-03-31"

[[cross_validation.blocks]]
train_start = "2022-02-01"
train_end = "2022-02-28"
test_start = "2022-03-01"
test_end = "2022-03-31"

[[cross_validation.blocks]]
train_start = "2024-04-01"
train_end = "2024-04-30"
test_start = "2024-05-01"
test_end = "2024-05-31"

# Hyperparameter Search Ranges for Bayesian Optimization
[hyperparameter_search]
# PSO Population Size
N_min = 25
N_max = 80

# PSO Acceleration Coefficients
C1_min = 0.5
C1_max = 3.5
C2_min = 0.5
C2_max = 3.0

# PSO Inertia Weight
omega_min = 0.1
omega_max = 0.9

# Function Calls Budget
f_calls_min = 600
f_calls_max = 2500

# Temporal Penalty Weight (continuity between days)
temporal_penalty_min = 0.0001
temporal_penalty_max = 0.2

# MAD Threshold (outlier detection)
mad_threshold_min = 6.0
mad_threshold_max = 12.0

# Liquidity Factor (outlier detection)
fator_liq_min = 0.001
fator_liq_max = 0.015

# L-BFGS Usage Probability (0=never, 1=always)
use_lbfgs_prob_min = 0.0
use_lbfgs_prob_max = 1.0